### ISSUE TITLE
Database update notifier using system clock

### ISSUE THREAD

**Issue by ShimSekai** [mdnpascual/Padherder_Extender#1]
I live in SA, my timezone is 4 hours ahead of PST. As soon as my computers clock hits midnight, whenever I access padherder I get the popup notification telling me to go update the database at padx, even though there's nothing to update.

**Comment by mdnpascual** [comment]
fix your timezone settings in your system clock. If you have set it correctly, then this should sync perfectly when the dungeons change daily. If you're saying you're 4 hours ahead of PST, then your time zone should've been set to UTC -4. Sounds like you're time zone is set currently at UTC -9?

In my case, padherder.com updates at 2am for me because my time zone is set to mst (UTC -7)
